package cloud.autotests.tests;

import cloud.autotests.config.demowebshop.App;
import cloud.autotests.helpers.DriverUtils;
import com.codeborne.selenide.Configuration;
import io.qameta.allure.Description;
import io.restassured.RestAssured;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.remote.DesiredCapabilities;

import static com.codeborne.selenide.Condition.text;
import static com.codeborne.selenide.Selenide.*;
import static com.codeborne.selenide.Selenide.executeJavaScript;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {

    @Test
    @DisplayName("Негативный сценарий. Аутентификация пользователя через номер карты.")
    void generatedTest() {
        step("Open https://online.vtb.ru/login", () -> {
            open("https://online.vtb.ru/login");
        });

        step("Set value in input CARD", () -> {
            String cardNumber = "12345678901234567";
            $(".masked-input_4jx7m9ib7").setValue(cardNumber);
        });

        step("Set value in input CARD", () -> {
            String cardNumber = "123456As$";
            $(".input-password_r4f509u3j").setValue(cardNumber);
        });

        step("Should be visible Error massage", () -> {
            $(".control-with-tips_pela2uj7w-hint-message").shouldHave(text("Неправильный номер карты"));
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://online.vtb.ru/login'", () ->
            open("https://online.vtb.ru/login"));

        step("Page title should have text 'Интернет-банк ВТБ Онлайн: вход в личный кабинет'", () -> {
            String expectedTitle = "Интернет-банк ВТБ Онлайн: вход в личный кабинет";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://online.vtb.ru/login'", () ->
            open("https://online.vtb.ru/login"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}